gerrit: fix user update without username
When admin login, it is already created in gerrit and the controller
fails because of missing username:
  HTTPError: 422 Client Error: Unprocessable Entity for url: fqdn/api/a/accounts/None

This changes prevents gerrit user creation without username and
it also make sure admin user mapping is properly set. Otherwise
this failure prevents other usermanger added after gerrit service.

Change-Id: If6d7899196cf05f25e0823b7e5d48f166880d623